from app.models.reconstruction import (
    AspectRatio,
    QualityMode,
    ReconstructionCreateJobResponse,
    ReconstructionJobRequest,
    ReconstructionJobStatus,
    ReconstructionJobStatusResponse,
    ReconstructionResult,
)
from app.models.report_schema import (
    CaseEvidenceBundle,
    Citation,
    EntityMention,
    EvidenceItem,
    EvidenceItemType,
    EventCandidate,
    GenerateReportJobAcceptedResponse,
    GenerateReportRequest,
    MediaAsset,
    MediaAssetKind,
    ReportArtifactRefs,
    ReportBlock,
    ReportBlockState,
    ReportBlockType,
    ReportDocument,
    ReportGenerationJobRecord,
    ReportGenerationJobStatus,
    ReportGenerationJobStatusResponse,
    ReportJobEvent,
    ReportProvenance,
    ReportSection,
    ReportStatus,
    SectionType,
    SourceSpan,
)

# Backward-compatible re-exports from the legacy schema so code that does
# ``from app.models import EvidenceType`` (etc.) still works.
from app.models.schema import (  # noqa: F811
    BLOCK_TYPES,
    EVIDENCE_TYPES,
    ContradictionSeverity,
    EvidenceType,
    SourceLocation,
    SourcePin,
    new_id,
)

__all__ = [
    # report_schema (reporting pipeline)
    "CaseEvidenceBundle",
    "Citation",
    "EntityMention",
    "EvidenceItem",
    "EvidenceItemType",
    "EventCandidate",
    "GenerateReportJobAcceptedResponse",
    "GenerateReportRequest",
    "MediaAsset",
    "MediaAssetKind",
    "ReportArtifactRefs",
    "ReportBlock",
    "ReportBlockState",
    "ReportBlockType",
    "ReportDocument",
    "ReportGenerationJobRecord",
    "ReportGenerationJobStatus",
    "ReportGenerationJobStatusResponse",
    "ReportJobEvent",
    "ReportProvenance",
    "ReportSection",
    "ReportStatus",
    "SectionType",
    "SourceSpan",
    # reconstruction
    "AspectRatio",
    "QualityMode",
    "ReconstructionCreateJobResponse",
    "ReconstructionJobRequest",
    "ReconstructionJobStatus",
    "ReconstructionJobStatusResponse",
    "ReconstructionResult",
    # legacy schema backward-compat
    "BLOCK_TYPES",
    "EVIDENCE_TYPES",
    "ContradictionSeverity",
    "EvidenceType",
    "SourceLocation",
    "SourcePin",
    "new_id",
]
